name: PlaywrightTests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.51.1-noble
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run unit-tests, then build and start application
        run: |
          npm test
          npm run build
          npm start &
          npx wait-on http://localhost:3000
          npx playwright test
